project:
  type: website
  output-dir: docs

website:
  title: "Wherewith.ai"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/WherewithAI/wherewithai-blog
format:
  html:
    theme:
      - cosmo
      - styles.scss
    css: styles.css



